name: Resuable Deploy
on:
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of deploy file
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          # name: dist-files # need to dynamic
          name: ${{ inputs.artifacts-name }}
      - name: List Files
        run: ls
      - name: Output Infor
        run: echo "Uploading"
