name: Resuable Deploy
on:
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of deploy file
        required: false
        default: dist
        type: string
      # secrets:
      #   some-scret:
      #     required: false
    outputs:
      result:
        description: The Result of steps
        value: ${{jobs.deploy.outputs.outcome}}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          # name: dist-files # need to dynamic
          name: ${{ inputs.artifacts-name }}
      - name: List Files
        run: ls
      - name: Output Infor
        run: echo "Uploading"
      - name: Set Result Output
        id: step-result
        run: echo "::set-output name=step-result::success"
